export const ABILITY_DETAIL_FETCH_START = 'ABILITY_DETAIL_FETCH_START'
export const ABILITY_DETAIL_FETCH_SUCCESS = 'ABILITY_DETAIL_FETCH_SUCCESS'
export const ABILITY_DETAIL_FETCH_ERROR = 'ABILITY_DETAIL_FETCH_ERROR'