export const ABILITY_LIST_FETCH_START: string = 'ABILITY_LIST_FETCH_START';
export const ABILITY_LIST_FETCH_SUCCESS: string = 'ABILITY_LIST_FETCH_SUCCESS';
export const ABILITY_LIST_FETCH_ERROR: string = 'ABILITY_LIST_FETCH_ERROR';
export const ABILITY_LIST_SET_PAGE: string = 'ABILITY_LIST_SET_PAGE';
